### ISSUE TITLE
Confirmation dialog before leaving reviews or lessons

### ISSUE THREAD

**Issue by Aralox** [WaniKani/Android-Notification#23]
Hi Alberto, I pulled and quickly modified your "next" branch to include some code that shows a dialog box before the user exits reviews or lessons. I did this because I keep accidentally pressing the back button during lessons and losing my progress. 

I wasn't sure what was the best way to give you the code; I use Android studio instead of Eclipse so it wasn't a trivial thing to commit & push my changes. I only changed the 'onBackPressed()' function in 'WebReviewActivity.java'. Here is a pastebin with the modified source file: http://pastebin.com/4t2FPWUf

Thanks for your work,
Aralox

**Comment by s84606** [comment]
Hi Aralox, thank you for your contribution. I've integrated your patch and updated the "next" branch.
In case you need/want a signed APK containing your patch, you can downloaded it from:
   https://www.dropbox.com/s/62b1a3k6q6n5shb/WaniKaniMobile-1.15.6pre6.apk?dl=0
Note that unfortunately I can't seriously maintain this project anymore, so I'm not distributing new releases on Google Play (volunteers are welcome :). However if you have more patches to share (also through a push request) I'll be appy to integrate them. 

Thanks!
   Alberto.
